### ISSUE TITLE
Errors on 1.13(Snapshot) world .mca file

### ISSUE THREAD

**Issue by wgaylord** [TkTech/PyNBT#13]
The following NBT file throws an error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pynbt\nbt.py", line 334, in __init__
    raise IOError('NBTFile does not begin with 0x0A.')
IOError: NBTFile does not begin with 0x0A.
```
This file tho is perfectly valid.  As NBTExplorer opens it and MC opens it just file.

[r.-1.-1.zip](https://github.com/TkTech/PyNBT/files/1537338/r.-1.-1.zip)

**Comment by wgaylord** [comment]
NVM Appears this is just because the LONG_ARRAY tag support has not been pushed to PyPi.

**Comment by wgaylord** [comment]
Error using github version.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pynbt\nbt.py", line 340, in __init__
    raise IOError('NBTFile does not begin with 0x0A.')
IOError: NBTFile does not begin with 0x0A.
```
